Add Bitcoin
Hargeon/wallet pull request #1
Opened 2021-09-01 16:54 UTC by Hargeon

# Tasks

- [ ] Deposit bitcoin
- [ ] Withdraw bitcoin
- [ ] Balance
- [ ] Tests

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2021-09-02 19:30 UTC, gordonBusyman requested changes

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +// can't add negative value
It is default behaviour no need to comment it

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +// can't add positive value
Same here

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +	if amount > 0 {
Why negative? 🤣

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/error.go
> +type InvalidPositiveAmount struct {
`InvalidPositiveAmount` -> `ErrNegativeAmount`

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/error.go
> +}
rm

2021-09-02 19:30 UTC, gordonBusyman commented on bitcoin/error.go
> +}
Actually just:
```
var (
	// ErrNegativeAmount ...
	ErrDepositNegativeAmount = errors.New("trying to deposit negative amount") // нуили текст можно получшн сделать
	// ErrWithdrawNegativeAmount ...
	ErrWithdrawNegativeAmount = errors.New("trying to withdraw negative amount")
```
should be enough

2021-09-02 19:30 UTC, gordonBusyman commented on wallet.go
> +}
One more function can be useful - get amount of bitcoins pretty printed, like 

`w.Balance()` -> `Output: 0.0532 BTC`

2021-09-02 19:40 UTC, Hargeon commented on go.mod
> +module "github.com/Hargeon/wallet"
Via Goland IDE(new->module)

2021-09-02 20:05 UTC, Hargeon commented on wallet.go
> +// Package wallet holds cryptocurrency. Now supports only Bitcoin
> `package XXX` should be the first line of the file

Do you mean to delete the comments? [here](https://go.dev/blog/godoc) describes comment of package should be first

2021-09-02 20:09 UTC, Hargeon commented on wallet.go
> +}
We should refactor **balance** filed if we will add new currency. I thing it is not good idea.

2021-09-02 20:41 UTC, Hargeon commented on bitcoin/bitcoin.go
> +// can't add negative value
Done

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/bitcoin.go
> +// can't add positive value
Done

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/bitcoin.go
> +	if amount > 0 {
Fixed)

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/bitcoin.go
> +	}
Fixed

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/error.go
> +type InvalidPositiveAmount struct {
Done

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/error.go
> +}
Done

2021-09-02 20:42 UTC, Hargeon commented on bitcoin/error.go
> +}
Done

2021-09-02 20:42 UTC, Hargeon commented on wallet.go
> +}
Done

2021-09-02 20:43 UTC, Hargeon commented on wallet.go
> +	wlt := Wallet{b}
Done

2021-09-02 20:44 UTC, Hargeon commented on wallet.go
> +// Package wallet holds cryptocurrency. Now supports only Bitcoin
> Please keep the structure clean - use folders for pkgs

What do you mean? I use bitcoin folder for bitcoin package

2021-09-06 11:18 UTC, gordonBusyman requested changes
- Please use linters, the standard set of linters will not allow the code without comments in Exported stuff
- Re-think the organization: where are you depositing your bitcoins^ in the wallet or in the bitcoin itself? (understand that bitcoin itself is a kind of wallet, but let`s move the deposit mutators to Wallet)

2021-09-06 11:18 UTC, gordonBusyman commented on bitcoin/error.go
> +	ErrNewBitcoinAmount       = errors.New("trying to create bitcoin with negative amount")
Add comments to Exported (Public)

2021-09-06 11:18 UTC, gordonBusyman commented on wallet.go
> +// Package wallet holds cryptocurrency. Now supports only Bitcoin
For the comment  you are right! Never seen is before

2021-09-06 11:18 UTC, gordonBusyman commented on wallet.go
> +// Package wallet holds cryptocurrency. Now supports only Bitcoin
I left a comment in `wallet` package not `bitcoin`

2021-09-06 11:18 UTC, gordonBusyman commented on go.mod
> +module "github.com/Hargeon/wallet"
try to init new project via `go mod init`

2021-09-06 11:18 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +func NewBitcoin(amount float64) (*Bitcoin, error) {
Add a comment it is public

2021-09-06 11:18 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +func (b *Bitcoin) DepositBitcoin(amount float64) error {
Add a comment it is public

2021-09-06 11:18 UTC, gordonBusyman commented on bitcoin/bitcoin.go
> +func (b *Bitcoin) WithdrawBitcoin(amount float64) error {
Add a comment it is public

2021-09-06 14:14 UTC, Hargeon commented on go.mod
> +module "github.com/Hargeon/wallet"
Done

2021-09-06 14:15 UTC, Hargeon commented on bitcoin/error.go
> +	ErrNewBitcoinAmount       = errors.New("trying to create bitcoin with negative amount")
Done

2021-09-06 14:15 UTC, Hargeon commented on bitcoin/bitcoin.go
> +func NewBitcoin(amount float64) (*Bitcoin, error) {
Done

2021-09-06 14:15 UTC, Hargeon commented on bitcoin/bitcoin.go
> +func (b *Bitcoin) DepositBitcoin(amount float64) error {
Done

2021-09-06 14:15 UTC, Hargeon commented on bitcoin/bitcoin.go
> +func (b *Bitcoin) WithdrawBitcoin(amount float64) error {
Done

2021-09-06 14:43 UTC, Hargeon commented on wallet.go
> +// Package wallet holds cryptocurrency. Now supports only Bitcoin
Done

2021-09-06 15:15 UTC, gordonBusyman approved these changes

2021-09-06 15:23 UTC, merged